// Generated by CoffeeScript 1.7.1
var FirstRay,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

FirstRay = (function(_super) {
  __extends(FirstRay, _super);

  function FirstRay(Game) {
    FirstRay.__super__.constructor.call(this, Game);
    this.name = '1st Ray';
    this.image = '1st-ray.png';
    this.hp = this.hpMax = 50;
    this.exp = 40;
    this.gil = 30;
    this.ap = 4;
  }

  return FirstRay;

})(Enemy);
