// Generated by CoffeeScript 1.7.1
var Cloud,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Cloud = (function(_super) {
  __extends(Cloud, _super);

  function Cloud(Game) {
    this.name = 'Cloud Strife';
    this.image = 'cloud.png';
    this.weapon = new BusterSword(Game, this);
    this.hpBase = 140;
    this.mpBase = 50;
    Cloud.__super__.constructor.call(this, Game);
  }

  return Cloud;

})(Character);
