// Generated by CoffeeScript 1.7.1
var BusterSword,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BusterSword = (function(_super) {
  __extends(BusterSword, _super);

  function BusterSword(Game, fighter) {
    BusterSword.__super__.constructor.call(this, Game, fighter);
    this.name = 'Buster Sword';
    this.type = 'broadsword';
    this.hits = 18;
    this.price = 170;
    this.zone = 1;
    this.delay = 5;
  }

  return BusterSword;

})(Weapon);
