// Generated by CoffeeScript 1.7.1
var GatlingGun,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

GatlingGun = (function(_super) {
  __extends(GatlingGun, _super);

  function GatlingGun() {
    this.name = 'Gatling Gun';
    this.type = 'gun-arm';
    this.hits = 14;
    this.price = 130;
    this.zone = 1;
  }

  return GatlingGun;

})(Weapon);
