// Generated by CoffeeScript 1.7.1
var Zone1,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Zone1 = (function(_super) {
  __extends(Zone1, _super);

  function Zone1(Game) {
    this.Game = Game;
    this.name = 'Sector 1 Reactor';
  }

  Zone1.prototype.opponents = function() {
    return [[new FirstRay(this.Game)]];
  };

  return Zone1;

})(Zone);
