// Generated by CoffeeScript 1.7.1
var Bolt,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Bolt = (function(_super) {
  __extends(Bolt, _super);

  function Bolt() {
    Bolt.__super__.constructor.call(this);
    this.name = 'Bolt';
    this.color = 'green';
    this.levelMax = 3;
    this.price = 600;
  }

  return Bolt;

})(Materia);
