// Generated by CoffeeScript 1.7.1
var Restore,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Restore = (function(_super) {
  __extends(Restore, _super);

  function Restore() {
    Restore.__super__.constructor.call(this);
    this.name = 'Restore';
    this.color = 'green';
    this.levelMax = 4;
    this.price = 750;
  }

  return Restore;

})(Materia);
