// Generated by CoffeeScript 1.7.1
var Battle;

Battle = (function() {
  Battle.prototype.commands = null;

  Battle.prototype.actions = [];

  Battle.prototype.action = null;

  Battle.prototype.exp = 0;

  Battle.prototype.gil = 0;

  Battle.prototype.ap = 0;

  function Battle(Game, opponents) {
    var character, opponent, _i, _j, _len, _len1, _ref, _ref1;
    this.Game = Game;
    this.opponents = opponents;
    this.commands = new Commands(this);
    this.Game.setMode('fight');
    _ref = this.opponents;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      opponent = _ref[_i];
      opponent.fight();
    }
    _ref1 = this.Game.getTeam();
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      character = _ref1[_j];
      character.fight();
    }
    this.run();
  }

  Battle.prototype.run = function() {
    return this.Game.$timeout((function(_this) {
      return function() {
        if (_this.actions.length > 0) {
          _this.action = _this.actions.shift();
          _this.action.exec(function() {
            _this.action.fighter.newTurn();
            return _this.action = null;
          });
        }
        return _this.run();
      };
    })(this), 1000);
  };

  Battle.prototype.end = function() {
    var character, remaining, _i, _len, _ref, _results;
    remaining = _.filter(this.opponents, function(enemy) {
      return enemy.hp > 0;
    }).length;
    if (remaining === 0) {
      this.opponents = [];
      this.Game.setMode('rewards');
      _ref = this.Game.getTeam();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        character = _ref[_i];
        character.setEXP(this.gil);
        _results.push(this.Game.setGil(this.gil));
      }
      return _results;
    }
  };

  return Battle;

})();
