// Generated by CoffeeScript 1.7.1
var Command;

Command = (function() {
  Command.prototype.fighter = null;

  Command.prototype.skills = [];

  function Command(fighter) {
    this.fighter = fighter;
    this.skills = this.fighter.skills();
  }

  return Command;

})();
