// Generated by CoffeeScript 1.7.1
var Commands;

Commands = (function() {
  Commands.prototype.list = [];

  Commands.prototype.current = null;

  Commands.prototype.isActive = false;

  function Commands(battle) {
    this.battle = battle;
  }

  Commands.prototype.add = function(command) {
    this.list.push(command);
    return this.display();
  };

  Commands.prototype.display = function(i) {
    if (i == null) {
      i = 0;
    }
    if (this.list.length > 0) {
      return this.current = this.list[i];
    }
  };

  Commands.prototype.close = function() {
    var index;
    index = _.indexOf(this.list, this.current);
    this.list.splice(index, 1);
    this.current = null;
    return this.display();
  };

  return Commands;

})();
