// Generated by CoffeeScript 1.7.1
var Enemy;

Enemy = (function() {
  function Enemy(Game) {
    this.Game = Game;
  }

  Enemy.prototype.fight = function() {};

  Enemy.prototype.getDamaged = function(damages) {
    this.hp -= damages;
    this.hp = Math.max(this.hp, 0);
    if (this.hp === 0) {
      this.Game.battle.exp += this.exp;
      this.Game.battle.gil += this.gil;
      this.Game.battle.ap += this.ap;
      return this.Game.battle.end();
    }
  };

  return Enemy;

})();
