// Generated by CoffeeScript 1.7.1
var Game;

Game = (function() {
  function Game($rootScope, $location, $cookieStore, $http, $timeout) {
    this.$rootScope = $rootScope;
    this.$location = $location;
    this.$cookieStore = $cookieStore;
    this.$http = $http;
    this.$timeout = $timeout;
    this._id = _.uniqueId();
    this.mode = 'home';
    this.gils = 200;
    this.characters = [];
    this.items = [];
    this.$rootScope.game = this;
    this.version = '0.2.1';
    this.time = 0;
    this.run();
  }

  Game.prototype.load = function() {
    var save;
    if (!this.loaded) {
      this.loaded = true;
      save = this.$cookieStore.get('game');
      if (save) {
        return this.extend(save);
      } else {
        return this.newGame();
      }
    }
  };

  Game.prototype.newGame = function() {
    var cloud;
    cloud = new Cloud(this);
    this.addCharacter(cloud).addItem(new Potion()).addItem(new Potion());
    return this.zone = new Zone1(this);
  };

  Game.prototype.setMode = function(mode) {
    this.mode = mode;
    return this.$location.path("/" + this.mode);
  };

  Game.prototype.addCharacter = function(character) {
    this.characters.push(character);
    return this;
  };

  Game.prototype.addItem = function(item) {
    this.items.push(item);
    return this;
  };

  Game.prototype.setGil = function(gil) {
    return this.gils += gil;
  };

  Game.prototype.getTeam = function() {
    return _.first(this.characters, 3);
  };

  Game.prototype.run = function() {
    return this.$timeout((function(_this) {
      return function() {
        _this.time++;
        return _this.run();
      };
    })(this), 1000);
  };

  Game.prototype.getTime = function() {
    var elapsed, hours, minutes, seconds;
    elapsed = this.time;
    hours = Math.floor(elapsed / 3600);
    elapsed -= hours * 3600;
    minutes = Math.floor(elapsed / 60);
    if (minutes < 10) {
      minutes = '0' + minutes;
    }
    seconds = elapsed - minutes * 60;
    if (seconds < 10) {
      seconds = '0' + seconds;
    }
    return hours + ':' + minutes + ':' + seconds;
  };

  Game.prototype.getRewards = function() {
    return this.setMode('home');
  };

  return Game;

})();
