// Generated by CoffeeScript 1.7.1
var Move;

Move = (function() {
  Move.prototype.fn = null;

  Move.prototype.ms = 0;

  function Move(fn, ms) {
    this.fn = fn;
    this.ms = ms;
  }

  return Move;

})();
